template = "https://github.com/giellalt/template-lang-und"
rev_id = 281
template_sha = "818353eecbfc8e1309992f6739dfde72a0afbec0"

[replacements]
__GLOTTOLOG_ID__ = "cent2127"
__REPO__ = "lang-esu"
__UND2C__ = "esu"
__UNDEFINED__ = "Central Yupik"
__UND__ = "esu"
