template = "https://github.com/giellalt/template-lang-und"
rev_id = 273
template_sha = "9f0fbd0d561cacc624db71c646d1ccc4d51920f6"

[replacements]
__GLOTTOLOG_ID__ = "cent2127"
__REPO__ = "lang-esu"
__UND2C__ = "esu"
__UNDEFINED__ = "Central Yupik"
__UND__ = "esu"
